def build(bld):
  source = [
    'python_bridge.cpp',
    'py_word_splitter.cpp',
    'py_binary_feature.cpp',
  ]

  bld.shlib(
    source = source,
    target = 'python_bridge',
    install_path = bld.env['LIBDIR'] + '/jubatus/plugin',
    use='JUBATUS_CORE PYTHON',
  )

def options(opt):
    pass

def configure(conf):
    pass
